### PR TITLE
Adding new mobile friendly UI

### PR DESCRIPTION
**Pull request by asgrant**
@drewwills, I tried my best to extract work that @rrglomsk did to update the UI on the Map Portlet. If you see anything out of the ordinary let me know and I can fix it from our code base. I removed all of the old jQuery UI and Fluid stuff also.

There are a few more upgrades I need to make after this (i.e. adding to search portlet api, help views, licensing in headers, etc).

screen shot 2015-06-03 at 3 56 24 pm
screen shot 2015-06-03 at 3 55 46 pm
screen shot 2015-06-03 at 3 55 24 pm

### CODE REVIEW

**Comment by asgrant** [comment]
Also I left in our images / json feed, figure it out be good demo data.

**Comment by asgrant** [comment]
@ChristianMurphy Josh at OU is looking at addressing this.

**Comment by Josh31415** [comment]
@ChristianMurphy I moved the demo data to a demo directory and documented it in the readme.

**Comment by ChristianMurphy** [comment]
@asgrant @Josh31415 Some merge conflicts have cropped up, could the conflicts be resolved so this can be merged in?

**Comment by asgrant** [comment]
@ChristianMurphy I'll talk with @Josh31415 and we'll get these problems resolved.

**Comment by asgrant** [comment]
@Josh31415 thank you for pushing this merge resolution. @ChristianMurphy can you look at this again? 👍

**Comment by ChristianMurphy** [comment]
Thanks @asgrant and @Josh31415!
The changes look good. :+1: 

GitHub showing that there are some remaining conflicts though:

**Conflicting files**
README.md
src/main/webapp/WEB-INF/jsp/mapView.jsp
src/main/webapp/css/map.css

**Comment by Josh31415** [comment]
@ChristianMurphy The conflict in the README.md is due to a comment that I added about the demo data. Should I remove it?

**Comment by ChristianMurphy** [comment]
@Josh31415 keep it, its helpful :+1:

**Comment by ChristianMurphy** [comment]
Progress!
One conflict remains *README.md*.
From the comment above it sounds like its already resolved on your local.
Stage, commit, and push then this PR should be good to go :star2:

**Comment by Josh31415** [comment]
The only conflict in the README.md is the note I added about the demo data. https://github.com/Jasig/MapPortlet/pull/13/conflicts

**Comment by ChristianMurphy** [comment]
Yep, that's the last remaining merge conflict.

**Comment by ChristianMurphy** [comment]
Thanks @asgrant and @Josh31415!

**Pull request merged**
